### ISSUE TITLE
the instance is not working/ installing !! 

### ISSUE THREAD

**Issue by simploita78** [intergrav/vital#3]
![Screenshot 2024-08-09 215323](https://github.com/user-attachments/assets/28894545-bf69-469f-b257-6f3d94beb0ea)

![proof 1](https://github.com/user-attachments/assets/2dc7f163-45e8-48fc-90ea-2d93ceb848af)

What to do now ?

**Comment by worldwidepixel** [comment]
What error are you experiencing?

**Comment by blryface** [comment]
Don't use issues for support, this is not a bug with the mod pack. If you want help with making your game work, use a server with some sort of community support

You can also join the Vital discord to ask questions about the mod pack

**Comment by simploita78** [comment]
> What error are you experiencing?
see the error below

![Screenshot 2024-08-09 215323](https://github.com/user-attachments/assets/11035fc3-0558-45a2-b41a-bff5b448a78a)

**Comment by simploita78** [comment]
> Don't use issues for support, this is not a bug with the mod pack. If you want help with making your game work, use a server with some sort of community support
> 
> You can also join the Vital discord to ask questions about the mod pack

ok then what ?
fine can you provide me the discord server link

**Comment by simploita78** [comment]
An error occured 
Error fetchingURL: error
decoding response body

> What error are you experiencing?

**Comment by blryface** [comment]
server link is https://discord.gg/wncdz7e8jy
